# Generated by Django 5.0 on 2023-12-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_phone', models.CharField(max_length=15)),
                ('GSTIN_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.userprofile')),
            ],
        ),
    ]
