# Generated by Django 5.0 on 2023-12-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashionapp", "0002_vendordetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendordetails",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="fashionapp.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("availability", models.IntegerField()),
                ("size", models.CharField(max_length=15)),
                ("colours", models.CharField(max_length=55)),
                ("description", models.CharField(max_length=555)),
                ("cost", models.IntegerField()),
                ("images", models.ImageField(upload_to="ProductImages/")),
                ("category", models.CharField(max_length=35)),
                ("sub_category", models.CharField(max_length=35)),
                (
                    "product_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionapp.vendordetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                ("quantity", models.IntegerField()),
                ("payment_details", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=60)),
                ("cost", models.IntegerField()),
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cust_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionapp.userprofile",
                    ),
                ),
                (
                    "vend_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionapp.vendordetails",
                    ),
                ),
                (
                    "product_ordered",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionapp.productdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_review", models.CharField(max_length=255)),
                ("ratings", models.IntegerField()),
                (
                    "review_pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionapp.productdetails",
                    ),
                ),
            ],
        ),
    ]
