# Generated by Django 5.0 on 2023-12-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashionapp", "0003_alter_vendordetails_user_profile_productdetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product_vendor",
            field=models.IntegerField(),
        ),
    ]
