# Generated by Django 5.0 on 2023-12-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashionapp", "0004_alter_productdetails_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="images",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
