# Generated by Django 5.0 on 2023-12-25 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fashionapp", "0006_usercart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercart",
            old_name="car_producrt",
            new_name="cart_product",
        ),
    ]
