# Generated by Django 5.0 on 2023-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0008_usercart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
