# Generated by Django 5.0 on 2024-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0010_alter_usercart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cost',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
